# Generated by Django 5.0.6 on 2024-05-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Idade', models.IntegerField()),
                ('Caracteristicas', models.CharField(max_length=255)),
            ],
        ),
    ]
