# Generated by Django 5.0.6 on 2024-05-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adotaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='Img_pet/'),
        ),
    ]
